# Identificador proporcionado por SEGDI-PCM
clientId=**********************
# Identificador proporcionado por SEGDI-PCM
clientSecret=***********************
# Direccion Ip y Puerto de escucha Firma Perú Invoker Integration
serverAddress=0.0.0.0:9091
# Clave secreta para generar Tokens
secretKeyJwt=nC23m84rtwi83nFQF4XAsAGs3d8q6k
# Usuario que accedera a la API
userAccessApi=usuarioAccesoApi
# Tiempo de expiración del Token en minutos. Ejemplo 5 minutos (Opcional)
timeExpireToken=5
# Certificado SSL/TLS (Opcional)
#certificateFileTls=cert.pem
# Clave Privada SSL/TLS  (Opcional)
#privateKeyFileTls=key.pem